/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'newsletter-subscribers': NewsletterSubscriber;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    landing: Landing;
    footer: Footer;
  };
  globalsSelect: {
    landing: LandingSelect<false> | LandingSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: 'it' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: string;
  email: string;
  consent: boolean;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: string | NewsletterSubscriber;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  consent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Gestisci i contenuti testuali e le immagini della landing page del sito.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing".
 */
export interface Landing {
  id: string;
  hero: HeroSectionProps;
  pillars?: PillarsSectionProps;
  sections: SectionsProps;
  formSection: FormSectionProps;
  project: ProjectSectionProps;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSectionProps".
 */
export interface HeroSectionProps {
  heading: string;
  subHeading: string;
  subHeroText: string;
  backgroundImage: string | Media;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillarsSectionProps".
 */
export interface PillarsSectionProps {
  items?:
    | {
        key: 'dimora' | 'gusto' | 'mirabilia' | 'amenita';
        title: string;
        subtitle: string;
        /**
         * Anchor per scroll (es: dimora, gusto, mirabilia, amenita)
         */
        anchorId: string;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionsProps".
 */
export interface SectionsProps {
  dimora: GalleryContentProps;
  gusto: GalleryContentProps;
  mirabilia: GalleryContentProps;
  amenita: ActivitySectionProps;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryContentProps".
 */
export interface GalleryContentProps {
  /**
   * Titolo della sezione (es: Dimora, Gusto, Mirabilia)
   */
  sectionTitle: string;
  /**
   * Titolo principale della sezione
   */
  title: string;
  /**
   * Sottotitolo della sezione
   */
  subtitle?: string | null;
  /**
   * Testo descrittivo della sezione
   */
  description: string;
  images: {
    image: string | Media;
    id?: string | null;
  }[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActivitySectionProps".
 */
export interface ActivitySectionProps {
  /**
   * Titolo della sezione (es: Amenità / Amenities)
   */
  sectionTitle: string;
  /**
   * Titolo della sezione (es: Amenità / Amenities)
   */
  title: string;
  /**
   * Sottotitolo della sezione (es: Amenità / Amenities)
   */
  subtitle?: string | null;
  /**
   * Descrizione della sezione
   */
  description?: string | null;
  cards: {
    cardtitle: string;
    cardDescription: string;
    image: string | Media;
    id?: string | null;
  }[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormSectionProps".
 */
export interface FormSectionProps {
  heading: string;
  description: string;
  /**
   * Testo sotto al form (es: privacy + riferimento alla disiscrizione). Il link lo gestiamo lato frontend.
   */
  footerText: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectSectionProps".
 */
export interface ProjectSectionProps {
  title: string;
  subtitle: string;
  /**
   * Frase evocativa / di chiusura
   */
  tagline: string;
  description: string;
  image: string | Media;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  footer: {
    address: string;
    contacts: {
      text: string;
      phone: string;
      email: string;
    };
    socials: {
      cta: string;
      instagram?: string | null;
      facebook?: string | null;
      linkedin?: string | null;
      tiktok?: string | null;
    };
    copyright: string;
    text: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing_select".
 */
export interface LandingSelect<T extends boolean = true> {
  hero?: T | HeroSectionPropsSelect<T>;
  pillars?: T | PillarsSectionPropsSelect<T>;
  sections?: T | SectionsPropsSelect<T>;
  formSection?: T | FormSectionPropsSelect<T>;
  project?: T | ProjectSectionPropsSelect<T>;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroSectionProps_select".
 */
export interface HeroSectionPropsSelect<T extends boolean = true> {
  heading?: T;
  subHeading?: T;
  subHeroText?: T;
  backgroundImage?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PillarsSectionProps_select".
 */
export interface PillarsSectionPropsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        key?: T;
        title?: T;
        subtitle?: T;
        anchorId?: T;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SectionsProps_select".
 */
export interface SectionsPropsSelect<T extends boolean = true> {
  dimora?: T | GalleryContentPropsSelect<T>;
  gusto?: T | GalleryContentPropsSelect<T>;
  mirabilia?: T | GalleryContentPropsSelect<T>;
  amenita?: T | ActivitySectionPropsSelect<T>;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryContentProps_select".
 */
export interface GalleryContentPropsSelect<T extends boolean = true> {
  sectionTitle?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ActivitySectionProps_select".
 */
export interface ActivitySectionPropsSelect<T extends boolean = true> {
  sectionTitle?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  cards?:
    | T
    | {
        cardtitle?: T;
        cardDescription?: T;
        image?: T;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormSectionProps_select".
 */
export interface FormSectionPropsSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  footerText?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectSectionProps_select".
 */
export interface ProjectSectionPropsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  tagline?: T;
  description?: T;
  image?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  footer?:
    | T
    | {
        address?: T;
        contacts?:
          | T
          | {
              text?: T;
              phone?: T;
              email?: T;
            };
        socials?:
          | T
          | {
              cta?: T;
              instagram?: T;
              facebook?: T;
              linkedin?: T;
              tiktok?: T;
            };
        copyright?: T;
        text?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}